#!/usr/bin/env bash
#A bash scrip that gives information about a domain
function domain_check {

	dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | \
		awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
	}
if [ $# -eq 1 ]
then
	sub_domains=("www" "lb-01" "web-01" "web-02")
	for i in "${sub_domains[@]}";
	do
		domain_check "$1" "$i"
	done
else
	domain_check "$1" "$2"
fi


