#!/usr/bin/env bash
# A bash script that configures a new Ubuntu machine
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
ufw allow 'Nginx HTTP'
service nginx restart

