#!/usr/bin/env bash
# redirect a file
apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
replace="server_name _;\n\tlocation \/redirect_me {\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}"

sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart

