#!/usr/bin/env bash
#configures an ubuntu machine to have a custom header X-Served-By

apt -y update
apt -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

host=$(hostname)

new_config="server_name _;\n\tadd_header X-Served-By $host;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$new_config/" /etc/nginx/sites-enabled/default

new_congif="location = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/location = \/404.ml {/$new_config/" /etc/nginx/sites-enabled/default

sudo service nginx restart
