#!/usr/bin/env bash
#Configure HAproxy so that it send traffic to web-01 and web-02

apt -y update
apt -y install haproxy

config=\
"
frontend ini_frontend
	bind *:80
	mode http
	default_backend ini_backend

backend ini_backend
	balance roundrobin
	server 303030-web-01 100.27.3.38:80 check
	server 303030-web-02 52.87.212.15:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
