#!/usr/bin/env bash
#A Bash script that configures a server to listen to port 80
cd /etc/nginx/sites-enabled/ || exit;
rm default;
ln -s /etc/nginx/sites-available/default default;
service nginx restart
