#!/usr/bin/env bash
#Tell the story of passwd

IFS=$'\n'
while read -r line
do
	IFS=':' read -r USERNAME PASSWORD USER_ID GROUP_ID user_idinfo HOME_DIRECTORY shell <<< "$line"

	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $shell. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $user_idinfo"
done</etc/passwd

